import networkx as nx
import matplotlib.pyplot as plt

G = nx.Graph()

G.add_nodes_from(["Modrice, smycka", "Modrice, Tyrsova", "Modricka cihelna", "Moravanska", "Moravanske lany", "Orechovska", "Bohunicka",
    "Ustredni hrbitov", "Ustredni hrbitov smycka", "Hluboka", "Celni", "Nemocnice Milosrdnych bratri", "Porici", "Mendlovo namesti",
    "Vystaviste", "Lipova", "Pisarky", "Brafova", "Stranskeho", "Vozovna Komin", "Komin, smycka", "Svratecka", "Branka", "Podlesi",
    "Kamenolom", "Zoologicka zahrada", "Pristaviste", "Rakovecka", "Kubickova", "Ondrouskova", "Ecerova", "Stary Liskovec, smycka",
    "Dunajska", "Osova", "Svermova", "Beloruska", "Krematorium", "Vsetinska", "Vojtova", "Kridlovicka", "Soukenicka", "Vaclavska",
    "Hybesova", "Nove sady", "Nove sady, smycka", "Silingrovo namesti", "Nemocnice u sv. Anny", "Komenskeho namesti", "Obilni trn",
    "Uvoz", "Vsetickova", "Heinrichova", "Namesti Miru", "Rosickeho namesti", "Mozolky", "Burianovo namesti", "Kralova", "Tabor",
    "Rybkova", "Konecneho namesti", "Grohova", "Ceska", "Nerudova", "Klusackova", "Tererova", "Dobrovskeho", "Skacelova", "Cervinkova",
    "Technicke muzeum", "Technologicky Park", "Reckocive", "Filkukova", "Koriskova", "Hudcova", "Tylova", "Semilasso", "Kralovo Pole",
    "Husitska", "Jungmannova", "Kartouzska", "Sumavska", "Hrncirska", "Pionyrska", "Antoninska", "Moravske namesti", "Namesti Svobody",
    "Namesti 28. rijna", "Malinovskeho", "Zelny Trh", "Hlavni nadrazi", "Detska nemocnice", "Jugoslavska", "Tomanova", "Zemedelska",
    "Lesnicka", "Bieblova", "Fugnerova", "Halasovo namesti", "Certova rokle", "Stefanikova Ctvrt", "Zdrahalova", "Tkalcovska",
    "Kornerova", "Vojenska nemocnice", "Kuldova", "Stara osada", "Babicka", "Obransky most", "Ctvery hony", "Obranska u skoly",
    "Proskovo namesti", "Malomericky most", "Cacovicka", "Tomkovo namesti", "Namesti Republiky", "Vozovna Husovice", "Mostecka",
    "Travnickova", "Uzka", "Zvonarka", "Kovarska", "Svatopetrska", "Konopna", "Komarov", "Vlhka", "Masna", "Zivotskeho", "Geislerova",
    "Buzkova", "Otakara Sevcika", "Delnicky dum", "Julianov", "Zidovsky hrbitov", "Krasneho", "Belohorska", "Bila hora", "Lisenska",
    "Novolisenska", "Masarova", "Kotlanova", "Lisen Jirova", "Lisen Mifkova", "Podstranska", "Stranska skala",])


G.add_edges_from(
    [ ("Modrice, smycka", "Modrice, Tyrsova"),
    ("Modrice, Tyrsova", "Modricka cihelna"),
    ("Modricka cihelna", "Moravanska"),
    ("Moravanska", "Moravanske lany"),
    ("Moravanske lany", "Orechovska"),
    ("Orechovska", "Bohunicka"),
    ("Bohunicka", "Ustredni hrbitov"),
    ("Ustredni hrbitov", "Hluboka"), ("Ustredni hrbitov", "Ustredni hrbitov smycka"),
    ("Hluboka", "Celni"),
    ("Celni", "Nemocnice Milosrdnych bratri"), ("Celni", "Krematorium"),
    ("Nemocnice Milosrdnych bratri", "Porici"),
    ("Porici", "Mendlovo namesti"), ("Porici", "Vaclavska"), ("Hybesova", "Vaclavska"),
    ("Mendlovo namesti", "Vystaviste"), ("Mendlovo namesti", "Nemocnice u sv. Anny"),
    ("Vystaviste", "Lipova"),
    ("Lipova", "Pisarky"),
    ("Pisarky", "Brafova"),
    ("Brafova", "Stranskeho"),
    ("Stranskeho", "Vozovna Komin"),
    ("Vozovna Komin", "Svratecka"), ("Vozovna Komin", "Komin, smycka"), ("Vozovna Komin", "Rosickeho namesti"),
    ("Svratecka", "Branka"),
    ("Branka", "Podlesi"),
    ("Podlesi", "Kamenolom"),
    ("Kamenolom", "Zoologicka zahrada"),
    ("Zoologicka zahrada", "Pristaviste"),
    ("Pristaviste", "Kubickova"), ("Pristaviste", "Rakovecka"),
    ("Kubickova", "Ondrouskova"),
    ("Ondrouskova", "Ecerova"),
    ("Stary Liskovec, smycka", "Dunajska"),
    ("Dunajska", "Osova"),
    ("Osova", "Svermova"),
    ("Svermova", "Beloruska"),
    ("Beloruska", "Krematorium"),
    ("Krematorium", "Celni"),
    ("Krematorium", "Vsetinska"),
    ("Vsetinska", "Vojtova"),
    ("Vojtova", "Kridlovicka"),
    ("Kridlovicka", "Soukenicka"),
    ("Soukenicka", "Silingrovo namesti"), ("Soukenicka", "Hybesova"), ("Soukenicka", "Nove sady"),
    ("Silingrovo namesti", "Nemocnice u sv. Anny"), ("Silingrovo namesti", "Komenskeho namesti"),
    ("Komenskeho namesti", "Obilni trn"), ("Komenskeho namesti", "Ceska"),
    ("Obilni trn", "Uvoz"),
    ("Uvoz", "Vsetickova"),
    ("Vsetickova", "Heinrichova"),
    ("Heinrichova", "Namesti Miru"),
    ("Nove sady, smycka", "Nove sady"),
    ("Hybesova", "Silingrovo namesti"), ("Hybesova", "Nove sady"),
    ("Ceska", "Grohova"), ("Ceska", "Moravske namesti"), ("Ceska", "Namesti Svobody"),
    ("Grohova", "Antoninska"),
    ("Antoninska", "Konecneho namesti"),
    ("Konecneho namesti", "Rybkova"), ("Konecneho namesti", "Nerudova"),
    ("Rybkova", "Tabor"),
    ("Tabor", "Kralova"),
    ("Kralova", "Burianovo namesti"),
    ("Burianovo namesti", "Mozolky"),
    ("Mozolky", "Rosickeho namesti"),
    ("Nerudova", "Klusackova"),
    ("Klusackova", "Tererova"),
    ("Tererova", "Dobrovskeho"),
    ("Dobrovskeho", "Skacelova"),
    ("Skacelova", "Cervinkova"),
    ("Cervinkova", "Technicke muzeum"),
    ("Technicke muzeum", "Technologicky Park"),
    ("Reckocive", "Filkukova"),
    ("Filkukova", "Koriskova"),
    ("Koriskova", "Hudcova"),
    ("Hudcova", "Tylova"),
    ("Tylova", "Semilasso"),
    ("Semilasso", "Husitska"), ("Semilasso", "Kralovo Pole"),
    ("Husitska", "Jungmannova"),
    ("Jungmannova", "Kartouzska"),
    ("Kartouzska", "Sumavska"),
    ("Sumavska", "Hrncirska"),
    ("Hrncirska", "Pionyrska"),
    ("Pionyrska", "Antoninska"),
    ("Antoninska", "Moravske namesti"),
    ("Moravske namesti", "Namesti Svobody"), ("Moravske namesti", "Namesti 28. rijna"), ("Moravske namesti", "Malinovskeho"),
    ("Namesti Svobody", "Zelny Trh"),
    ("Zelny Trh", "Nove sady"), ("Zelny Trh", "Hlavni nadrazi"),
    ("Namesti 28. rijna", "Detska nemocnice"),
    ("Detska nemocnice", "Jugoslavska"),
    ("Jugoslavska", "Tomanova"),
    ("Tomanova", "Zemedelska"),
    ("Zemedelska", "Lesnicka"),
    ("Lesnicka", "Bieblova"),
    ("Bieblova", "Fugnerova"),
    ("Fugnerova", "Halasovo namesti"),
    ("Halasovo namesti", "Certova rokle"),
    ("Malinovskeho", "Hlavni nadrazi"), ("Malinovskeho", "Kornerova"),
    ("Kornerova", "Tkalcovska"),
    ("Tkalcovska", "Vojenska nemocnice"), ("Tkalcovska", "Travnickova"), ("Tkalcovska", "Jugoslavska"),
    ("Jugoslavska", "Zdrahalova"), ("Jugoslavska", "Travnickova"),
    ("Zdrahalova", "Stefanikova Ctvrt"),
    ("Vojenska nemocnice", "Kuldova"),
    ("Kuldova", "Stara osada"),
    ("Travnickova", "Mostecka"),
    ("Mostecka", "Vozovna Husovice"),
    ("Vozovna Husovice", "Namesti Republiky"),
    ("Namesti Republiky", "Tomkovo namesti"),
    ("Tomkovo namesti", "Cacovicka"),
    ("Cacovicka", "Malomericky most"),
    ("Malomericky most", "Proskovo namesti"),
    ("Proskovo namesti", "Obranska u skoly"),
    ("Obranska u skoly", "Ctvery hony"),
    ("Ctvery hony", "Obransky most"),
    ("Obransky most", "Babicka"),
    ("Hlavni nadrazi", "Vlhka"), ("Hlavni nadrazi", "Uzka"),
    ("Uzka", "Zvonarka"),
    ("Zvonarka", "Kovarska"),
    ("Kovarska", "Svatopetrska"),
    ("Svatopetrska", "Konopna"),
    ("Konopna", "Komarov"),
    ("Vlhka", "Masna"),
    ("Masna", "Zivotskeho"),
    ("Zivotskeho", "Geislerova"),
    ("Geislerova", "Buzkova"), ("Geislerova", "Zidovsky hrbitov"),
    ("Buzkova", "Otakara Sevcika"),
    ("Otakara Sevcika", "Delnicky dum"),
    ("Delnicky dum", "Julianov"),
    ("Zidovsky hrbitov", "Krasneho"),
    ("Krasneho", "Belohorska"), ("Krasneho", "Podstranska"),
    ("Podstranska", "Stranska skala"),
    ("Belohorska", "Bila hora"),
    ("Bila hora", "Lisenska"),
    ("Lisenska", "Novolisenska"),
    ("Novolisenska", "Masarova"),
    ("Masarova", "Kotlanova"),
    ("Kotlanova", "Lisen Jirova"),
    ("Lisen Jirova", "Lisen Mifkova"),
    ]
)

pos = nx.kamada_kawai_layout(G)

nx.draw(G, pos, with_labels=True, node_color="lightgreen", font_size=5)

plt.show()